### ISSUE TITLE
Feature Request: Auto Tip

### ISSUE THREAD

**Issue by 10Meisterbaelle** [Antimoxs/HyPlus#6]
Automatically tips all active Network Boosters, allowing the user to collect coins, karma, and experience (earnable currencies) over time.

This mod already exists and is open source: https://autotip.pro/
You could just implement it as long as you follow the license

**Comment by Antimoxs** [comment]
Hi! 
This feature will be implemented into the new HyPlus for LabyMod4 since LabyMod3 is no longer supported.
:D
